# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XYScaner_Pro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XYScaner_Pro
  pod 'Firebase/Core'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationInMobi'

  target 'XYScaner_ProUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
